<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CfopSeeder extends Seeder
{
    public function run(): void
    {
        $cfop = [
            // Entradas no Estado (1xxx)
            ['1101', 'Compra p/ industrialização', 'entrada'],
            ['1102', 'Compra p/ comercialização', 'entrada'],
            ['1111', 'Compra p/ industrialização de produtor rural', 'entrada'],
            ['1113', 'Compra p/ comercialização de produtor rural', 'entrada'],
            ['1201', 'Devolução de venda de industrialização', 'entrada'],
            ['1202', 'Devolução de venda de comercialização', 'entrada'],
            ['1400', 'Entrada de mercadoria em consignação', 'entrada'],
            ['1401', 'Entrada de matéria-prima em consignação', 'entrada'],
            ['1410', 'Retorno de mercadoria em consignação', 'entrada'],
            ['1500', 'Entrada de bem do ativo imobilizado', 'entrada'],
            ['1550', 'Entrada de material de uso/consumo', 'entrada'],
            ['1601', 'Entrada de mercadoria p/ exportação', 'entrada'],
            ['1650', 'Entrada de combustível', 'entrada'],
            ['1900', 'Outras entradas no estado', 'entrada'],
            ['1901', 'Entrada p/ industrialização por conta de terceiros', 'entrada'],
            ['1902', 'Retorno de mercadoria remetida p/ industrialização', 'entrada'],
            ['1903', 'Entrada de mercadoria remetida p/ industrialização', 'entrada'],
            ['1904', 'Retorno simbólico de mercadoria remetida p/ industrialização', 'entrada'],
            ['1905', 'Entrada de mercadoria recebida p/ depósito fechado', 'entrada'],
            ['1906', 'Retorno de mercadoria remetida p/ depósito fechado', 'entrada'],
            ['1907', 'Entrada simbólica de mercadoria em depósito fechado', 'entrada'],
            ['1908', 'Entrada de bem por conta de contrato de comodato', 'entrada'],
            ['1909', 'Entrada de mercadoria em bonificação', 'entrada'],
            ['1910', 'Entrada de amostra grátis', 'entrada'],
            ['1911', 'Entrada de mercadoria em doação', 'entrada'],
            ['1912', 'Entrada de mercadoria em permuta', 'entrada'],
            ['1913', 'Entrada de mercadoria em garantia/substituição', 'entrada'],
            ['1914', 'Entrada de mercadoria em arrendamento mercantil', 'entrada'],
            ['1915', 'Entrada de mercadoria em comodato', 'entrada'],
            ['1916', 'Entrada de mercadoria usada', 'entrada'],
            ['1917', 'Entrada de mercadoria de cooperativa', 'entrada'],
            ['1918', 'Entrada de mercadoria de produtor rural', 'entrada'],
            ['1919', 'Entrada de mercadoria de fabricante', 'entrada'],
            ['1920', 'Entrada de mercadoria de outro estabelecimento', 'entrada'],
            ['1921', 'Entrada de mercadoria de importador', 'entrada'],
            ['1922', 'Entrada de mercadoria de comerciante atacadista', 'entrada'],
            ['1923', 'Entrada de mercadoria de comerciante varejista', 'entrada'],
            ['1924', 'Entrada de mercadoria de órgão público', 'entrada'],
            ['1925', 'Entrada de mercadoria de entidade sem fins lucrativos', 'entrada'],
            ['1926', 'Entrada de mercadoria de pessoa física', 'entrada'],
            ['1931', 'Entrada de mercadoria de produtor rural pessoa física', 'entrada'],
            ['1932', 'Entrada de mercadoria de produtor rural pessoa jurídica', 'entrada'],
            ['1933', 'Entrada de mercadoria de fabricante pessoa jurídica', 'entrada'],
            ['1949', 'Outras entradas de mercadoria', 'entrada'],

            // Entradas Fora do Estado (2xxx)
            ['2101', 'Compra p/ industrialização fora do estado', 'entrada'],
            ['2102', 'Compra p/ comercialização fora do estado', 'entrada'],
            ['2201', 'Devolução de venda de industrialização fora do estado', 'entrada'],
            ['2202', 'Devolução de venda de comercialização fora do estado', 'entrada'],
            ['2401', 'Entrada de mercadoria em consignação fora do estado', 'entrada'],
            ['2500', 'Entrada de bem do ativo imobilizado fora do estado', 'entrada'],
            ['2550', 'Entrada de material de uso/consumo fora do estado', 'entrada'],
            ['2900', 'Outras entradas fora do estado', 'entrada'],

            // Entradas do Exterior (3xxx)
            ['3101', 'Compra p/ industrialização do exterior', 'entrada'],
            ['3102', 'Compra p/ comercialização do exterior', 'entrada'],
            ['3120', 'Desembaraço aduaneiro de mercadoria importada', 'entrada'],
            ['3201', 'Devolução de venda ao exterior', 'entrada'],
            ['3500', 'Entrada de bem do ativo imobilizado do exterior', 'entrada'],
            ['3550', 'Entrada de material de uso/consumo do exterior', 'entrada'],
            ['3900', 'Outras entradas do exterior', 'entrada'],

            // Saídas no Estado (5xxx)
            ['5101', 'Venda de industrialização no estado', 'saida'],
            ['5102', 'Venda de comercialização no estado', 'saida'],
            ['5103', 'Venda de produção rural no estado', 'saida'],
            ['5104', 'Venda de mercadoria adquirida de terceiro no estado', 'saida'],
            ['5105', 'Venda de mercadoria importada no estado', 'saida'],
            ['5106', 'Venda de mercadoria de terceiros no estado', 'saida'],
            ['5110', 'Venda de mercadoria em consignação no estado', 'saida'],
            ['5111', 'Venda de mercadoria em consignação mercantil no estado', 'saida'],
            ['5112', 'Venda de mercadoria em consignação industrial no estado', 'saida'],
            ['5113', 'Venda de mercadoria recebida em consignação no estado', 'saida'],
            ['5114', 'Venda de mercadoria recebida em consignação mercantil no estado', 'saida'],
            ['5115', 'Venda de mercadoria recebida em consignação industrial no estado', 'saida'],
            ['5116', 'Venda de mercadoria em consignação de produtor rural no estado', 'saida'],
            ['5117', 'Venda de mercadoria em consignação de terceiro no estado', 'saida'],
            ['5118', 'Venda de mercadoria de produtor rural no estado', 'saida'],
            ['5119', 'Venda de mercadoria de fabricante no estado', 'saida'],
            ['5120', 'Venda de mercadoria de comerciante atacadista no estado', 'saida'],
            ['5121', 'Venda de mercadoria de comerciante varejista no estado', 'saida'],
            ['5122', 'Venda de mercadoria de importador no estado', 'saida'],
            ['5123', 'Venda de mercadoria de produtor rural pessoa física no estado', 'saida'],
            ['5124', 'Venda de mercadoria de produtor rural pessoa jurídica no estado', 'saida'],
            ['5201', 'Devolução de compra de industrialização no estado', 'saida'],
            ['5202', 'Devolução de compra de comercialização no estado', 'saida'],
            ['5250', 'Devolução de compra de ativo imobilizado no estado', 'saida'],
            ['5401', 'Remessa de mercadoria em consignação no estado', 'saida'],
            ['5402', 'Remessa de mercadoria em consignação mercantil no estado', 'saida'],
            ['5403', 'Remessa de mercadoria em consignação industrial no estado', 'saida'],
            ['5404', 'Remessa de mercadoria em consignação de produtor rural no estado', 'saida'],
            ['5405', 'Remessa de mercadoria em consignação de terceiro no estado', 'saida'],
            ['5501', 'Remessa de bem do ativo imobilizado no estado', 'saida'],
            ['5550', 'Remessa de material de uso/consumo no estado', 'saida'],
            ['5601', 'Remessa de mercadoria para exportação no estado', 'saida'],
            ['5650', 'Remessa de combustível no estado', 'saida'],
            ['5901', 'Remessa para industrialização por conta de terceiro no estado', 'saida'],
            ['5902', 'Retorno de mercadoria recebida para industrialização no estado', 'saida'],
            ['5903', 'Remessa para depósito fechado no estado', 'saida'],
            ['5904', 'Retorno de mercadoria de depósito fechado no estado', 'saida'],
            ['5905', 'Remessa simbólica de mercadoria para depósito fechado no estado', 'saida'],
            ['5906', 'Remessa de mercadoria em bonificação no estado', 'saida'],
            ['5907', 'Remessa de amostra grátis no estado', 'saida'],
            ['5908', 'Remessa de mercadoria em doação no estado', 'saida'],
            ['5909', 'Remessa de mercadoria em permuta no estado', 'saida'],
            ['5910', 'Remessa de mercadoria em garantia/substituição no estado', 'saida'],
            ['5911', 'Remessa de mercadoria em arrendamento mercantil no estado', 'saida'],
            ['5912', 'Remessa de mercadoria em comodato no estado', 'saida'],
            ['5913', 'Remessa de mercadoria usada no estado', 'saida'],
            ['5914', 'Remessa de mercadoria de cooperativa no estado', 'saida'],
            ['5915', 'Remessa de mercadoria para venda fora do estabelecimento no estado', 'saida'],
            ['5920', 'Venda de mercadoria para entrege futura no estado', 'saida'],
            ['5921', 'Venda de mercadoria a consumidor final no estado', 'saida'],
            ['5922', 'Venda a consumidor final por E-commerce no estado', 'saida'],
            ['5923', 'Venda a consumidor final por telemarketing no estado', 'saida'],
            ['5924', 'Venda a consumidor final por catálogo no estado', 'saida'],
            ['5925', 'Venda a consumidor final por venda ambulante no estado', 'saida'],
            ['5926', 'Venda a consumidor final por venda em feira no estado', 'saida'],
            ['5927', 'Venda a consumidor final por venda em exposição no estado', 'saida'],
            ['5928', 'Venda a consumidor final por venda em leilão no estado', 'saida'],
            ['5929', 'Venda a consumidor final por outras modalidades no estado', 'saida'],
            ['5930', 'Venda a órgão público no estado', 'saida'],
            ['5931', 'Venda a entidade sem fins lucrativos no estado', 'saida'],
            ['5932', 'Venda a pessoa física no estado', 'saida'],
            ['5933', 'Venda a pessoa jurídica no estado', 'saida'],
            ['5934', 'Venda a produtor rural no estado', 'saida'],
            ['5935', 'Venda a fabricante no estado', 'saida'],
            ['5936', 'Venda a comerciante atacadista no estado', 'saida'],
            ['5937', 'Venda a comerciante varejista no estado', 'saida'],
            ['5938', 'Venda a importador no estado', 'saida'],
            ['5949', 'Outras saídas no estado', 'saida'],

            // Saídas Fora do Estado (6xxx)
            ['6101', 'Venda de industrialização fora do estado', 'saida'],
            ['6102', 'Venda de comercialização fora do estado', 'saida'],
            ['6103', 'Venda de produção rural fora do estado', 'saida'],
            ['6104', 'Venda de mercadoria adquirida de terceiro fora do estado', 'saida'],
            ['6105', 'Venda de mercadoria importada fora do estado', 'saida'],
            ['6106', 'Venda de mercadoria de terceiros fora do estado', 'saida'],
            ['6110', 'Venda de mercadoria em consignação fora do estado', 'saida'],
            ['6201', 'Devolução de compra de industrialização fora do estado', 'saida'],
            ['6202', 'Devolução de compra de comercialização fora do estado', 'saida'],
            ['6401', 'Remessa de mercadoria em consignação fora do estado', 'saida'],
            ['6500', 'Remessa de bem do ativo imobilizado fora do estado', 'saida'],
            ['6550', 'Remessa de material de uso/consumo fora do estado', 'saida'],
            ['6601', 'Remessa de mercadoria para exportação fora do estado', 'saida'],
            ['6900', 'Outras saídas fora do estado', 'saida'],

            // Saídas para o Exterior (7xxx)
            ['7101', 'Venda de industrialização ao exterior', 'saida'],
            ['7102', 'Venda de comercialização ao exterior', 'saida'],
            ['7103', 'Venda de produção rural ao exterior', 'saida'],
            ['7120', 'Venda de mercadoria adquirida de terceiro ao exterior', 'saida'],
            ['7121', 'Venda de mercadoria importada ao exterior', 'saida'],
            ['7201', 'Devolução de compra ao exterior', 'saida'],
            ['7500', 'Remessa de bem do ativo imobilizado ao exterior', 'saida'],
            ['7900', 'Outras saídas ao exterior', 'saida'],
        ];

        $data = [];
        foreach ($cfop as $item) {
            $data[] = ['codigo' => $item[0], 'descricao' => $item[1], 'aplicacao' => $item[2], 'ativo' => true];
        }
        DB::table('cfop')->insertOrIgnore($data);
    }
}
